"""`gd-agents` — the orchestrator's command line.

Separate from `globalmart` on purpose. That one builds workspaces; this one talks to them.
They share a repository because GlobalMart is the proving ground, and share no code because
this package has to work against any GoodData org to be worth anything to a customer.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

from gd_agents.profile import build_registry, discovery_findings
from gd_agents.registry import DEFAULT_REGISTRY_PATH, Registry, RegistryError
from gd_agents.transport import Host, TransportError

FINDINGS_PATH = Path("docs/a2a-gaps.md")


def _host(args: argparse.Namespace) -> Host:
    token = os.environ.get(args.token_env)
    if not token:
        raise RegistryError(
            f"No token in ${args.token_env}. Set it, or pass --token-env with the right name."
        )
    return Host(url=args.host, token=token)


def cmd_profile(args: argparse.Namespace) -> int:
    """Build each workspace's routing description by querying the workspace.

    Writes the registry the orchestrator loads, and the discovery findings — what the
    profiler had to reach for is the first item on the AIS-55 gap list, so it is recorded
    from a real run rather than reconstructed later.
    """
    workspaces = [w.strip() for w in args.workspaces.split(",") if w.strip()]
    if not workspaces:
        print("error: --workspaces is empty", file=sys.stderr)
        return 1

    registry, probes = build_registry(_host(args), workspaces, token_env=args.token_env)

    for entry in registry.entries:
        print(f"\n== {entry.id}  [{entry.title}]")
        print(f"   {entry.description}")

    findings = discovery_findings(probes)
    if findings:
        print("\nDiscovery findings:")
        for finding in findings:
            print(f"  * {finding}")

    if not args.apply:
        print(f"\nREHEARSAL — nothing written. Re-run with --apply to write {args.out}.")
        return 0

    registry.write(Path(args.out))
    print(f"\nWrote {len(registry.entries)} workspace(s) to {args.out}")

    if findings:
        path = Path(args.findings)
        path.parent.mkdir(parents=True, exist_ok=True)
        body = "\n".join(f"- {finding}" for finding in findings)
        path.write_text(
            "# What an orchestrator needs from GoodData, and what is missing\n\n"
            "## Agent discovery\n\n"
            "Generated by `gd-agents profile` from a real run against "
            f"{len(probes)} workspace(s) on {registry.entries[0].profiled_at}. "
            "Not written from memory.\n\n"
            f"{body}\n",
            encoding="utf-8",
        )
        print(f"Wrote {len(findings)} finding(s) to {path}")
    return 0


def cmd_route(args: argparse.Namespace) -> int:
    """Measure routing across the whole script. No lanes are called.

    Routing is a discrete decision, so it can be measured without a single A2A call — which
    makes "how reliably does the question pick the right workspaces" answerable in a minute
    for pennies, rather than an hour of real agent calls. That separability is the main
    practical argument for an explicit router over a tool-calling loop.
    """
    from gd_agents.orchestrator.plan import PlanError, Prior, make_client, plan
    from gd_agents.script import Question, RouteReport, compare, load_script

    registry = Registry.load(Path(args.registry))
    questions, conversations = load_script(Path(args.script))

    # A conversation's turns are scored *in their thread*. Scoring them standalone measures
    # a question nobody asked: "which of them converted best?" has no antecedent on its own,
    # and the router rightly returns nothing. The history given here is the expectation, not
    # a real reply — which keeps this lane-free while still resolving the references.
    threads: list[tuple[str, list[tuple[Question, tuple[Prior, ...]]]]] = [
        ("", [(q, ()) for q in questions])
    ]
    if args.turns:
        for conversation in conversations:
            scored: list[tuple[Question, tuple[Prior, ...]]] = []
            history: list[Prior] = []
            for turn in conversation.turns:
                # A `reply_to` turn is not routed at all — it answers one workspace's
                # question on that workspace's own conversation. Scoring it as a routing
                # decision measures something that never happens.
                if not turn.reply_to:
                    scored.append((turn, tuple(history)))
                history.append(Prior(question=turn.question, workspaces=tuple(turn.expect)))
            threads.append((conversation.id, scored))

    total = sum(len(items) for _, items in threads)
    client, model = make_client()
    print(f"model  : {model}")
    print(f"scoring: {total} question(s) against {args.script}\n")

    report = RouteReport()
    for label, items in threads:
        if label:
            print(f"  -- {label}")
        for question, prior in items:
            try:
                result = plan(question.question, registry, client=client, model=model, history=prior)
            except PlanError as error:
                # A `from_memory` turn is *meant* to route nowhere — "summarise what we have
                # established" asks about the conversation. Choosing no workspace is the
                # right answer there, and scoring it as a failure would teach the prompt the
                # wrong lesson.
                outcome = compare(question, ())
                if not outcome.exact():
                    outcome.error = str(error)[:160]
                report.outcomes.append(outcome)
                mark = "ok  " if outcome.exact() else "ERROR"
                detail = "no workspace needed" if outcome.exact() else str(error)[:80]
                print(f"  {question.id:34} {mark} {detail}")
                continue
            outcome = compare(question, result.workspaces())
            outcome.tokens_in, outcome.tokens_out = result.tokens_in, result.tokens_out
            report.outcomes.append(outcome)
            mark = "ok  " if outcome.exact() else "MISS"
            print(f"  {question.id:34} {mark} -> {', '.join(outcome.chosen) or 'none'}")

    print()
    for line in report.summary_lines():
        print(f"  {line}")
    return 0 if report.exact() == len(report.outcomes) else 1


def _lanes(registry: Registry) -> dict[str, object]:
    from gd_agents.a2a.client import A2ALane

    token = os.environ.get(registry.token_env)
    if not token:
        raise RegistryError(f"No token in ${registry.token_env}.")
    host = Host(url=registry.host, token=token)
    return {
        entry.id: A2ALane(host=host, workspace=entry.id, description=entry.description)
        for entry in registry.entries
    }


def cmd_ask(args: argparse.Namespace) -> int:
    """One question, answered from several workspaces, printed.

    The command-line viewer. Enough to demo "prompt in, merged answer out" without a server,
    and the same payload the page renders — so what is shown here is what a host would get.
    """
    from gd_agents.orchestrator.run import ask

    registry = Registry.load(Path(args.registry))
    run = ask(
        args.question,
        registry,
        _lanes(registry),  # type: ignore[arg-type]
        inject_failure=args.inject_failure,
    )

    if args.json:
        print(json.dumps(run.payload(), indent=2))
        return 0

    for line in run.summary_lines():
        print(f"  {line}")
    print("\n--- answer ---\n")
    print(run.reply())
    return 0 if run.merged.ok() or not run.merged.combinable else 1


def cmd_mcp_probe(args: argparse.Namespace) -> int:
    """Measure what the MCP endpoint offers and what each discovery route costs.

    FEAT-014's counterpart to FEAT-009's profiler, and it earned its place immediately: the
    spec was written expecting seventeen tools with four selected, and the endpoint
    advertises three. Everything downstream depends on knowing that, so it is established by
    asking rather than by reading.
    """
    from gd_agents.mcp.probe import probe_all, report

    registry = Registry.load(Path(args.registry))
    workspaces = [w.strip() for w in args.workspaces.split(",") if w.strip()] or list(registry.ids())
    token = os.environ.get(registry.token_env)
    if not token:
        raise RegistryError(f"No token in ${registry.token_env}.")

    probes = probe_all(Host(url=registry.host, token=token), workspaces)
    for probe in probes:
        for line in probe.summary_lines():
            print(f"  {line}")
        print()

    body = report(probes)
    if not args.apply:
        print(f"REHEARSAL — nothing written. Re-run with --apply to write {args.out}.")
        return 0
    path = Path(args.out)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")
    print(f"Wrote {path}")
    return 0


def cmd_rehearse(args: argparse.Namespace) -> int:
    """Run the scripted conversations end to end, against the live agents.

    `route` measures the router alone and is cheap. This is the expensive half: every turn
    actually asked, in order, over one session — so contexts carry, follow-ups resolve
    "those" against a real earlier turn, and the enrich and reply paths are exercised rather
    than described.

    It exists because "verified" has to mean something reproducible. A conversation in the
    script that nobody has run is a guess about what the agents will do, and the agents are
    the part we do not control.
    """
    from gd_agents.orchestrator.plan import make_client
    from gd_agents.orchestrator.run import ask, enrich, respond
    from gd_agents.orchestrator.session import Session
    from gd_agents.script import compare, load_script

    registry = Registry.load(Path(args.registry))
    _, conversations = load_script(Path(args.script))
    wanted = {c.strip() for c in (args.only or "").split(",") if c.strip()}
    if wanted:
        conversations = tuple(c for c in conversations if c.id in wanted)
        if not conversations:
            print(f"error: no conversation matching {args.only}", file=sys.stderr)
            return 1

    lanes = _lanes(registry)
    client, model = make_client()
    print(f"model   : {model}")
    print(f"running : {len(conversations)} conversation(s), "
          f"{sum(len(c.turns) for c in conversations)} turn(s) — this calls live agents\n")

    misroutes = 0
    broken = 0
    for conversation in conversations:
        print(f"== {conversation.id}  ({len(conversation.turns)} turns)")
        session = Session()
        for number, turn in enumerate(conversation.turns, start=1):
            try:
                if turn.enrich:
                    run = enrich(registry, lanes, session, client=client, model=model)  # type: ignore[arg-type]
                elif turn.reply_to:
                    run = respond(
                        lanes,  # type: ignore[arg-type]
                        session,
                        turn.reply_to,
                        turn.question,
                        client=client,
                        model=model,
                    )
                else:
                    run = ask(
                        turn.question,
                        registry,
                        lanes,  # type: ignore[arg-type]
                        session=session,
                        client=client,
                        model=model,
                        inject_failure=turn.inject_failure,
                    )
            except Exception as error:  # noqa: BLE001 - one bad turn must not end the rehearsal
                broken += 1
                print(f"  {number}. ERROR {type(error).__name__}: {str(error)[:100]}")
                continue

            chosen = tuple(a.workspace for a in run.lanes.answers)
            outcome = compare(turn, chosen)
            mark = "ok  " if outcome.exact() else "MISS"
            if not outcome.exact():
                misroutes += 1
            failed = [a.workspace for a in run.lanes.answers if not a.ok()]
            pending = [a.workspace for a in run.lanes.answers if a.input_required]
            # Total, and how much of it was the agents. The difference is the two model
            # calls, and it is worth seeing separately: a slow turn is usually a slow lane,
            # but not always — one measured turn spent 633s of which the lanes were a small
            # part, and reading that as agent latency would have aimed the fix at the wrong
            # layer.
            orchestrator_ms = max(0, run.total_ms - run.lanes.wall_ms)
            state = (
                f"{'combined' if run.merged.combinable else 'separate':9}"
                f" {run.total_ms:>6} ms  lanes {run.lanes.wall_ms:>6}  model {orchestrator_ms:>6}"
                + (f"  FAILED {', '.join(failed)}" if failed else "")
                + (f"  ASKS {', '.join(pending)}" if pending else "")
            )
            print(f"  {number}. {mark} {', '.join(chosen) or 'none':52} {state}")
            if not outcome.exact():
                print(f"       expected {', '.join(turn.expect)}")
            if args.verbose:
                print(f"       q: {turn.question}")
                print(f"       a: {run.reply()[:300]}")
        print()

    print(f"  conversations     : {len(conversations)}")
    print(f"  turns             : {sum(len(c.turns) for c in conversations)}")
    print(f"  routing misses    : {misroutes}")
    print(f"  turns that errored: {broken}")
    return 0 if not broken else 1


def cmd_serve(args: argparse.Namespace) -> int:
    """Serve the minimal viewer.

    It stands where Portal Copilot stands and is meant to be deleted. Its only job is to
    make a turn watchable; the payload is the actual interface.
    """
    from gd_agents.server.app import serve

    registry = Registry.load(Path(args.registry))
    serve(registry, _lanes(registry), host=args.host, port=args.port)  # type: ignore[arg-type]
    return 0


def cmd_registry_show(args: argparse.Namespace) -> int:
    """Print the routing prompt block, so what the router sees is inspectable."""
    registry = Registry.load(Path(args.registry))
    print(f"host   : {registry.host}")
    print(f"token  : ${registry.token_env}")
    print(f"\n{registry.prompt_block()}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="gd-agents", description=__doc__)
    actions = parser.add_subparsers(dest="command", required=True)

    profile = actions.add_parser(
        "profile", help="generate workspace routing descriptions by querying the workspaces"
    )
    profile.add_argument("--host", required=True, help="GoodData org base url")
    profile.add_argument(
        "--token-env",
        default="GLOBALMART_TOKEN__DEMO_CLOUD",
        help="name of the env var holding the API token — never the token itself",
    )
    profile.add_argument("--workspaces", required=True, help="comma-separated workspace ids")
    profile.add_argument("--out", default=str(DEFAULT_REGISTRY_PATH))
    profile.add_argument("--findings", default=str(FINDINGS_PATH))
    profile.add_argument("--apply", action="store_true", help="required to write anything")
    profile.set_defaults(func=cmd_profile)

    route = actions.add_parser(
        "route", help="measure routing across the question script, without calling any lane"
    )
    route.add_argument("--registry", default=str(DEFAULT_REGISTRY_PATH))
    route.add_argument("--script", default="config/questions.yaml")
    route.add_argument("--turns", action="store_true", help="also score every turn of every conversation")
    route.set_defaults(func=cmd_route)

    rehearse = actions.add_parser(
        "rehearse", help="run the scripted conversations end to end against the live agents"
    )
    rehearse.add_argument("--registry", default=str(DEFAULT_REGISTRY_PATH))
    rehearse.add_argument("--script", default="config/questions.yaml")
    rehearse.add_argument("--only", default="", help="comma-separated conversation ids")
    rehearse.add_argument("-v", "--verbose", action="store_true", help="print each question and reply")
    rehearse.set_defaults(func=cmd_rehearse)

    mcp_probe = actions.add_parser(
        "mcp-probe", help="measure what each workspace's MCP endpoint offers, and what it costs"
    )
    mcp_probe.add_argument("--registry", default=str(DEFAULT_REGISTRY_PATH))
    mcp_probe.add_argument("--workspaces", default="", help="comma-separated; defaults to the registry")
    mcp_probe.add_argument("--out", default="docs/mcp-findings.md")
    mcp_probe.add_argument("--apply", action="store_true", help="write the findings file")
    mcp_probe.set_defaults(func=cmd_mcp_probe)

    ask_cmd = actions.add_parser("ask", help="ask one question across the registered workspaces")
    ask_cmd.add_argument("question")
    ask_cmd.add_argument("--registry", default=str(DEFAULT_REGISTRY_PATH))
    ask_cmd.add_argument("--json", action="store_true", help="print the payload a host would get")
    ask_cmd.add_argument("--inject-failure", help="force one workspace to fail, for the demo")
    ask_cmd.set_defaults(func=cmd_ask)

    serve_cmd = actions.add_parser("serve", help="serve the minimal viewer")
    serve_cmd.add_argument("--registry", default=str(DEFAULT_REGISTRY_PATH))
    serve_cmd.add_argument("--host", default="127.0.0.1")
    serve_cmd.add_argument("--port", type=int, default=8900)
    serve_cmd.set_defaults(func=cmd_serve)

    show = actions.add_parser("registry", help="show the registry as the router sees it")
    show.add_argument("--registry", default=str(DEFAULT_REGISTRY_PATH))
    show.set_defaults(func=cmd_registry_show)

    args = parser.parse_args(argv)
    try:
        exit_code: int = args.func(args)
    except (RegistryError, TransportError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    return exit_code


if __name__ == "__main__":
    raise SystemExit(main())
