"""`gd-agents` — the orchestrator's command line.

Separate from `globalmart` on purpose. That one builds workspaces; this one talks to them.
They share a repository because GlobalMart is the proving ground, and share no code because
this package has to work against any GoodData org to be worth anything to a customer.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

from gd_agents.profile import build_registry, discovery_findings
from gd_agents.registry import DEFAULT_REGISTRY_PATH, Registry, RegistryError
from gd_agents.transport import Host, TransportError

FINDINGS_PATH = Path("docs/a2a-gaps.md")


def _host(args: argparse.Namespace) -> Host:
    token = os.environ.get(args.token_env)
    if not token:
        raise RegistryError(
            f"No token in ${args.token_env}. Set it, or pass --token-env with the right name."
        )
    return Host(url=args.host, token=token)


def cmd_profile(args: argparse.Namespace) -> int:
    """Build each workspace's routing description by querying the workspace.

    Writes the registry the orchestrator loads, and the discovery findings — what the
    profiler had to reach for is the first item on the AIS-55 gap list, so it is recorded
    from a real run rather than reconstructed later.
    """
    workspaces = [w.strip() for w in args.workspaces.split(",") if w.strip()]
    if not workspaces:
        print("error: --workspaces is empty", file=sys.stderr)
        return 1

    registry, probes = build_registry(_host(args), workspaces, token_env=args.token_env)

    for entry in registry.entries:
        print(f"\n== {entry.id}  [{entry.title}]")
        print(f"   {entry.description}")

    findings = discovery_findings(probes)
    if findings:
        print("\nDiscovery findings:")
        for finding in findings:
            print(f"  * {finding}")

    if not args.apply:
        print(f"\nREHEARSAL — nothing written. Re-run with --apply to write {args.out}.")
        return 0

    registry.write(Path(args.out))
    print(f"\nWrote {len(registry.entries)} workspace(s) to {args.out}")

    if findings:
        path = Path(args.findings)
        path.parent.mkdir(parents=True, exist_ok=True)
        body = "\n".join(f"- {finding}" for finding in findings)
        path.write_text(
            "# What an orchestrator needs from GoodData, and what is missing\n\n"
            "## Agent discovery\n\n"
            "Generated by `gd-agents profile` from a real run against "
            f"{len(probes)} workspace(s) on {registry.entries[0].profiled_at}. "
            "Not written from memory.\n\n"
            f"{body}\n",
            encoding="utf-8",
        )
        print(f"Wrote {len(findings)} finding(s) to {path}")
    return 0


def cmd_registry_show(args: argparse.Namespace) -> int:
    """Print the routing prompt block, so what the router sees is inspectable."""
    registry = Registry.load(Path(args.registry))
    print(f"host   : {registry.host}")
    print(f"token  : ${registry.token_env}")
    print(f"\n{registry.prompt_block()}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="gd-agents", description=__doc__)
    actions = parser.add_subparsers(dest="command", required=True)

    profile = actions.add_parser(
        "profile", help="generate workspace routing descriptions by querying the workspaces"
    )
    profile.add_argument("--host", required=True, help="GoodData org base url")
    profile.add_argument(
        "--token-env",
        default="GLOBALMART_TOKEN__DEMO_CLOUD",
        help="name of the env var holding the API token — never the token itself",
    )
    profile.add_argument("--workspaces", required=True, help="comma-separated workspace ids")
    profile.add_argument("--out", default=str(DEFAULT_REGISTRY_PATH))
    profile.add_argument("--findings", default=str(FINDINGS_PATH))
    profile.add_argument("--apply", action="store_true", help="required to write anything")
    profile.set_defaults(func=cmd_profile)

    show = actions.add_parser("registry", help="show the registry as the router sees it")
    show.add_argument("--registry", default=str(DEFAULT_REGISTRY_PATH))
    show.set_defaults(func=cmd_registry_show)

    args = parser.parse_args(argv)
    try:
        exit_code: int = args.func(args)
    except (RegistryError, TransportError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    return exit_code


if __name__ == "__main__":
    raise SystemExit(main())
