"""`gd-agents` — the orchestrator's command line.

Separate from `globalmart` on purpose. That one builds workspaces; this one talks to them.
They share a repository because GlobalMart is the proving ground, and share no code because
this package has to work against any GoodData org to be worth anything to a customer.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

from gd_agents.profile import build_registry, discovery_findings
from gd_agents.registry import DEFAULT_REGISTRY_PATH, Registry, RegistryError
from gd_agents.transport import Host, TransportError

FINDINGS_PATH = Path("docs/a2a-gaps.md")


def _host(args: argparse.Namespace) -> Host:
    token = os.environ.get(args.token_env)
    if not token:
        raise RegistryError(
            f"No token in ${args.token_env}. Set it, or pass --token-env with the right name."
        )
    return Host(url=args.host, token=token)


def cmd_profile(args: argparse.Namespace) -> int:
    """Build each workspace's routing description by querying the workspace.

    Writes the registry the orchestrator loads, and the discovery findings — what the
    profiler had to reach for is the first item on the AIS-55 gap list, so it is recorded
    from a real run rather than reconstructed later.
    """
    workspaces = [w.strip() for w in args.workspaces.split(",") if w.strip()]
    if not workspaces:
        print("error: --workspaces is empty", file=sys.stderr)
        return 1

    registry, probes = build_registry(_host(args), workspaces, token_env=args.token_env)

    for entry in registry.entries:
        print(f"\n== {entry.id}  [{entry.title}]")
        print(f"   {entry.description}")

    findings = discovery_findings(probes)
    if findings:
        print("\nDiscovery findings:")
        for finding in findings:
            print(f"  * {finding}")

    if not args.apply:
        print(f"\nREHEARSAL — nothing written. Re-run with --apply to write {args.out}.")
        return 0

    registry.write(Path(args.out))
    print(f"\nWrote {len(registry.entries)} workspace(s) to {args.out}")

    if findings:
        path = Path(args.findings)
        path.parent.mkdir(parents=True, exist_ok=True)
        body = "\n".join(f"- {finding}" for finding in findings)
        path.write_text(
            "# What an orchestrator needs from GoodData, and what is missing\n\n"
            "## Agent discovery\n\n"
            "Generated by `gd-agents profile` from a real run against "
            f"{len(probes)} workspace(s) on {registry.entries[0].profiled_at}. "
            "Not written from memory.\n\n"
            f"{body}\n",
            encoding="utf-8",
        )
        print(f"Wrote {len(findings)} finding(s) to {path}")
    return 0


def cmd_route(args: argparse.Namespace) -> int:
    """Measure routing across the whole script. No lanes are called.

    Routing is a discrete decision, so it can be measured without a single A2A call — which
    makes "how reliably does the question pick the right workspaces" answerable in a minute
    for pennies, rather than an hour of real agent calls. That separability is the main
    practical argument for an explicit router over a tool-calling loop.
    """
    from gd_agents.orchestrator.plan import PlanError, make_client, plan
    from gd_agents.script import RouteReport, compare, load_script

    registry = Registry.load(Path(args.registry))
    questions, conversations = load_script(Path(args.script))
    if args.turns:
        questions = questions + tuple(turn for conversation in conversations for turn in conversation.turns)

    client, model = make_client()
    print(f"model  : {model}")
    print(f"scoring: {len(questions)} question(s) against config/questions.yaml\n")

    report = RouteReport()
    for question in questions:
        try:
            result = plan(question.question, registry, client=client, model=model)
        except PlanError as error:
            outcome = compare(question, ())
            outcome.error = str(error)[:160]
            report.outcomes.append(outcome)
            print(f"  {question.id:26} ERROR {str(error)[:80]}")
            continue
        outcome = compare(question, result.workspaces())
        outcome.tokens_in, outcome.tokens_out = result.tokens_in, result.tokens_out
        report.outcomes.append(outcome)
        mark = "ok  " if outcome.exact() else "MISS"
        print(f"  {question.id:26} {mark} -> {', '.join(outcome.chosen) or 'none'}")

    print()
    for line in report.summary_lines():
        print(f"  {line}")
    return 0 if report.exact() == len(report.outcomes) else 1


def _lanes(registry: Registry) -> dict[str, object]:
    from gd_agents.a2a.client import A2ALane

    token = os.environ.get(registry.token_env)
    if not token:
        raise RegistryError(f"No token in ${registry.token_env}.")
    host = Host(url=registry.host, token=token)
    return {
        entry.id: A2ALane(host=host, workspace=entry.id, description=entry.description)
        for entry in registry.entries
    }


def cmd_ask(args: argparse.Namespace) -> int:
    """One question, answered from several workspaces, printed.

    The command-line viewer. Enough to demo "prompt in, merged answer out" without a server,
    and the same payload the page renders — so what is shown here is what a host would get.
    """
    from gd_agents.orchestrator.run import ask

    registry = Registry.load(Path(args.registry))
    run = ask(
        args.question,
        registry,
        _lanes(registry),  # type: ignore[arg-type]
        inject_failure=args.inject_failure,
    )

    if args.json:
        print(json.dumps(run.payload(), indent=2))
        return 0

    for line in run.summary_lines():
        print(f"  {line}")
    print("\n--- answer ---\n")
    print(run.reply())
    return 0 if run.merged.ok() or not run.merged.combinable else 1


def cmd_serve(args: argparse.Namespace) -> int:
    """Serve the minimal viewer.

    It stands where Portal Copilot stands and is meant to be deleted. Its only job is to
    make a turn watchable; the payload is the actual interface.
    """
    from gd_agents.server.app import serve

    registry = Registry.load(Path(args.registry))
    serve(registry, _lanes(registry), host=args.host, port=args.port)  # type: ignore[arg-type]
    return 0


def cmd_registry_show(args: argparse.Namespace) -> int:
    """Print the routing prompt block, so what the router sees is inspectable."""
    registry = Registry.load(Path(args.registry))
    print(f"host   : {registry.host}")
    print(f"token  : ${registry.token_env}")
    print(f"\n{registry.prompt_block()}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="gd-agents", description=__doc__)
    actions = parser.add_subparsers(dest="command", required=True)

    profile = actions.add_parser(
        "profile", help="generate workspace routing descriptions by querying the workspaces"
    )
    profile.add_argument("--host", required=True, help="GoodData org base url")
    profile.add_argument(
        "--token-env",
        default="GLOBALMART_TOKEN__DEMO_CLOUD",
        help="name of the env var holding the API token — never the token itself",
    )
    profile.add_argument("--workspaces", required=True, help="comma-separated workspace ids")
    profile.add_argument("--out", default=str(DEFAULT_REGISTRY_PATH))
    profile.add_argument("--findings", default=str(FINDINGS_PATH))
    profile.add_argument("--apply", action="store_true", help="required to write anything")
    profile.set_defaults(func=cmd_profile)

    route = actions.add_parser(
        "route", help="measure routing across the question script, without calling any lane"
    )
    route.add_argument("--registry", default=str(DEFAULT_REGISTRY_PATH))
    route.add_argument("--script", default="config/questions.yaml")
    route.add_argument("--turns", action="store_true", help="also score every turn of every conversation")
    route.set_defaults(func=cmd_route)

    ask_cmd = actions.add_parser("ask", help="ask one question across the registered workspaces")
    ask_cmd.add_argument("question")
    ask_cmd.add_argument("--registry", default=str(DEFAULT_REGISTRY_PATH))
    ask_cmd.add_argument("--json", action="store_true", help="print the payload a host would get")
    ask_cmd.add_argument("--inject-failure", help="force one workspace to fail, for the demo")
    ask_cmd.set_defaults(func=cmd_ask)

    serve_cmd = actions.add_parser("serve", help="serve the minimal viewer")
    serve_cmd.add_argument("--registry", default=str(DEFAULT_REGISTRY_PATH))
    serve_cmd.add_argument("--host", default="127.0.0.1")
    serve_cmd.add_argument("--port", type=int, default=8900)
    serve_cmd.set_defaults(func=cmd_serve)

    show = actions.add_parser("registry", help="show the registry as the router sees it")
    show.add_argument("--registry", default=str(DEFAULT_REGISTRY_PATH))
    show.set_defaults(func=cmd_registry_show)

    args = parser.parse_args(argv)
    try:
        exit_code: int = args.func(args)
    except (RegistryError, TransportError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    return exit_code


if __name__ == "__main__":
    raise SystemExit(main())
