"""The tool definitions a sub-agent is given, fetched once and committed.

`tools/list` does not name the analytical tools — the endpoint is a gateway — so their
schemas have to come from `search_tools`. Fetching them on every question would be both slow
and a distortion: a real integrator ships these definitions with their client, the way any
MCP host does, and would not pay for them per question. So they are fetched once by
`gd-agents mcp-tools --apply`, written to `config/mcp-tools.json`, and reviewed in a diff.

That is the same discipline as `config/agents.yaml` for the A2A arm — the thing the
orchestrator knows about a workspace is data, generated by asking, and committed so a change
is visible.

**The one-off cost is reported rather than hidden.** Discovering these schemas is real work
that an MCP integrator has to do, so `mcp-tools` prints what it cost. It just is not charged
to each question, because that would measure our impatience rather than the protocol.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from gd_agents.mcp.client import DEFAULT_TOOLS, MCPClient

DEFAULT_TOOLS_PATH = Path("config/mcp-tools.json")

#: One search per tool. `search_tools` is semantic, so the tool's own name is the query most
#: likely to return it — and the result is checked by name rather than trusted by rank.
SEARCH_HINT = "{name}: what it does and what arguments it takes"


class ToolsetError(Exception):
    """The tool definitions could not be fetched or loaded."""


def fetch_definitions(client: MCPClient, names: tuple[str, ...] = DEFAULT_TOOLS) -> dict[str, Any]:
    """Every named tool's definition, by asking the gateway about each one.

    A tool that cannot be found is an error rather than a silent omission: a sub-agent handed
    four tools when it was promised five would quietly measure something else.
    """
    found: dict[str, Any] = {}
    for name in names:
        raw = client.call_gateway("search_tools", query=SEARCH_HINT.format(name=name))
        try:
            candidates = json.loads(raw)
        except json.JSONDecodeError as error:
            raise ToolsetError(f"search_tools answered with non-JSON for {name!r}") from error
        match = next(
            (c for c in candidates if isinstance(c, dict) and c.get("name") == name),
            None,
        )
        if match is None:
            raise ToolsetError(
                f"{name!r} was not among the tools search_tools returned. Either the endpoint no "
                "longer offers it, or the tool set in client.py names something that never existed."
            )
        found[name] = {
            "name": name,
            "description": str(match.get("description") or "").strip(),
            "input_schema": match.get("inputSchema") or {"type": "object", "properties": {}},
        }
    return found


def write_definitions(definitions: dict[str, Any], path: Path = DEFAULT_TOOLS_PATH) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(definitions, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def load_definitions(path: Path = DEFAULT_TOOLS_PATH) -> dict[str, Any]:
    if not path.exists():
        raise ToolsetError(
            f"No tool definitions at {path}. Run `gd-agents mcp-tools --apply` to fetch them."
        )
    try:
        return dict(json.loads(path.read_text(encoding="utf-8")))
    except json.JSONDecodeError as error:
        raise ToolsetError(f"{path} is not valid JSON: {error}") from error


def anthropic_tools(
    definitions: dict[str, Any], names: tuple[str, ...] = DEFAULT_TOOLS
) -> list[dict[str, Any]]:
    """The definitions in the shape a model expects.

    Descriptions are passed through as GoodData wrote them. Rewriting them to suit our loop
    would be putting a thumb on the scale — `execute_query`'s own description is where the
    round-trip cost is stated ("Get IDs first with list_workspace_metrics or
    list_workspace_attributes"), and that sentence belongs in the measurement.
    """
    missing = [name for name in names if name not in definitions]
    if missing:
        raise ToolsetError(f"tool definitions are missing {', '.join(missing)}; re-run `mcp-tools`")
    return [
        {
            "name": name,
            "description": definitions[name]["description"],
            "input_schema": definitions[name]["input_schema"],
        }
        for name in names
    ]


def describe(definitions: dict[str, Any]) -> list[str]:
    """What shipping these definitions costs a sub-agent, per question, in context."""
    lines = []
    total = 0
    for name, entry in sorted(definitions.items()):
        size = len(json.dumps(entry))
        total += size
        lines.append(f"  {name:28} {size // 4:>6,} tok")
    lines.append(f"  {'every question pays':28} {total // 4:>6,} tok")
    return lines
